### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by shravanchndr** [Li-Chongyi/Zero-DCE#7]
```
r1,r2,r3,r4,r5,r6,r7,r8 = torch.split(x_r, 3, dim=1)
x = x + r1*(torch.pow(x,2)-x)
x = x + r2*(torch.pow(x,2)-x)
x = x + r3*(torch.pow(x,2)-x)
enhance_image_1 = x + r4*(torch.pow(x,2)-x)		
x = enhance_image_1 + r5*(torch.pow(enhance_image_1,2)-enhance_image_1)		
x = x + r6*(torch.pow(x,2)-x)	
x = x + r7*(torch.pow(x,2)-x)
enhance_image = x + r8*(torch.pow(x,2)-x)
r = torch.cat([r1,r2,r3,r4,r5,r6,r7,r8],1)
```

Can you please explain what's happening in this part of the code, in model.py. Thanks!
Also I tried without using enhance_image_1, and used x only instead and still gave good results, so why is that used?

**Comment by Li-Chongyi** [comment]
Hi,

Please refer to our paper for more details.

Yes, when iteratively using all estimated parameters, the initial result is
getting better (in an iterative manner). The same results also can be found
in our framework.

Also, you can only use the x and remove the iteration (I mean that removing
the iteration). The results are also not bad because of the effective curve
function.

shravanchndr <notifications@github.com> 于2020年7月26日周日 下午10:00写道：

**Comment by shravanchndr** [comment]
Understood. Thanks! :+1:
